name: CI

env:
  ACTIONS_RUNNER_DEBUG: "true"
  ACTIONS_STEP_DEBUG: "true"

on:
  push:
    branches: [ trunk ]
  pull_request:
    branches: [ trunk ]
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        include:
          - name: self-hosted mac
            os: macos-self
    name: ${{matrix.name || matrix.os || 'Tests' }}
    runs-on: self-hosted
    container: ${{matrix.container}}
    steps:
    - uses: actions/checkout@v2
    - run: ./test.sh
   
